-- Table: "Renew"."Utilities"

---DROP TABLE "Renew"."Util_Energy";

CREATE TABLE "Renew"."Util_Energy"
(
    year character varying COLLATE pg_catalog."default",
    month character varying COLLATE pg_catalog."default",
    state character varying COLLATE pg_catalog."default",
    util_num character varying COLLATE pg_catalog."default",
    util_name character varying COLLATE pg_catalog."default",
    status character varying COLLATE pg_catalog."default",
    type character varying COLLATE pg_catalog."default",
    res_cap_photo	NUMERIC (10, 2) default 0,
com_cap_phot	NUMERIC (10, 2) default 0,
ind_cap_photo	NUMERIC (10, 2) default 0,
trans_cap_photo	NUMERIC (10, 2) default 0,
total_cap_photo	NUMERIC (10, 2) default 0,
res_cust_photo	NUMERIC (10, 2) default 0,
com_cust_photo	NUMERIC (10, 2) default 0,
ind_cust_photo	NUMERIC (10, 2) default 0,
trans_cust_photo	NUMERIC (10, 2) default 0,
total_cust_photo	NUMERIC (10, 2) default 0,
res_stor_cap_photo	NUMERIC (10, 2) default 0,
com_stor_cap_photo	NUMERIC (10, 2) default 0,
ind_stor_cap_photo	NUMERIC (10, 2) default 0,
trans_stor_cap_phot	NUMERIC (10, 2) default 0,
total_stor_cap_photo	NUMERIC (10, 2) default 0,
res_stor_cust_photo	NUMERIC (10, 2) default 0,
com_stor_cust_photo	NUMERIC (10, 2) default 0,
ind_stor_cust_photo	NUMERIC (10, 2) default 0,
trans_stor_cust_photo	NUMERIC (10, 2) default 0,
tot_stor_cust_photo	NUMERIC (10, 2) default 0,
res_vir_cap_photo	NUMERIC (10, 2) default 0,
com_vir_cap_photo	NUMERIC (10, 2) default 0,
ind_vir_cap_photo	NUMERIC (10, 2) default 0,
tran_vir_cap_photo	NUMERIC (10, 2) default 0,
total_vir_cap_photo	NUMERIC (10, 2) default 0,
res_vir_cust_photo	NUMERIC (10, 2) default 0,
com_vir_cust_photo	NUMERIC (10, 2) default 0,
ind_vir_cust_photo	NUMERIC (10, 2) default 0,
tran_vir_cust_photo	NUMERIC (10, 2) default 0,
total_vir_cust_photo	NUMERIC (10, 2) default 0,
res_soldback_photo	NUMERIC (10, 2) default 0,
com_soldback_photo	NUMERIC (10, 2) default 0,
ind_soldback_photo	NUMERIC (10, 2) default 0,
tran_soldback_photo	NUMERIC (10, 2) default 0,
total_soldback_photo	NUMERIC (10, 2) default 0,
res_cap_wind	NUMERIC (10, 2) default 0,
com_cap_wind	NUMERIC (10, 2) default 0,
ind_cap_wind	NUMERIC (10, 2) default 0,
tran_cap_wind	NUMERIC (10, 2) default 0,
total_cap_wind	NUMERIC (10, 2) default 0,
res_cust_wind	NUMERIC (10, 2) default 0,
com_cust_wind	NUMERIC (10, 2) default 0,
ind_cust_wind	NUMERIC (10, 2) default 0,
tran_cust_wind	NUMERIC (10, 2) default 0,
total_cust_wind	NUMERIC (10, 2) default 0,
res_soldback_wind	NUMERIC (10, 2) default 0,
com_soldback_wind	NUMERIC (10, 2) default 0,
ind_soldback_wind	NUMERIC (10, 2) default 0,
tran_soldback_wind	NUMERIC (10, 2) default 0,
total_soldback_wind	NUMERIC (10, 2) default 0,
res_cap_other	NUMERIC (10, 2) default 0,
com_cap_other	NUMERIC (10, 2) default 0,
ind_cap_other	NUMERIC (10, 2) default 0,
tran_cap_other	NUMERIC (10, 2) default 0,
total_cap_other	NUMERIC (10, 2) default 0,
res_cust_other	NUMERIC (10, 2) default 0,
com_cust_other	NUMERIC (10, 2) default 0,
ind_cust_other	NUMERIC (10, 2) default 0,
tran_cust_other	NUMERIC (10, 2) default 0,
total_cust_other	NUMERIC (10, 2) default 0,
res_soldback_other	NUMERIC (10, 2) default 0,
com_soldback_other	NUMERIC (10, 2) default 0,
ind_soldback_other	NUMERIC (10, 2) default 0,
tran_soldback_other	NUMERIC (10, 2) default 0,
total_soldback_other	NUMERIC (10, 2) default 0,
res_cap_all	NUMERIC (10, 2) default 0,
com_cap_all	NUMERIC (10, 2) default 0,
ind_cap_all	NUMERIC (10, 2) default 0,
trans_cap_all	NUMERIC (10, 2) default 0,
total_cap_all	NUMERIC (10, 2) default 0,
res_cust_all	NUMERIC (10, 2) default 0,
com_cust_all	NUMERIC (10, 2) default 0,
ind_cust_all	NUMERIC (10, 2) default 0,
tran_cust_all	NUMERIC (10, 2) default 0,
total_custall	NUMERIC (10, 2) default 0,
res_soldback_all	NUMERIC (10, 2) default 0,
com_soldback_all	NUMERIC (10, 2) default 0,
ind_soldback_all	NUMERIC (10, 2) default 0,
tran_soldback_all	NUMERIC (10, 2) default 0,
total_soldback_all	NUMERIC (10, 2) default 0
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE "Renew"."Util_Energy"
    OWNER to postgres;
	
COPY "Renew"."Util_Energy" from 'c:/Electricity_by_Utility.csv' delimiter ',' csv header;